// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import SettingsController from "./settings_controller"
application.register("settings", SettingsController)

import LoginController from "./login_controller"
application.register("login", LoginController)

import ProfileController from "./profile_controller"
application.register("profile", ProfileController)
